
RESTORE FILELISTONLY FROM 
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_01.bak',
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_02.bak',
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_03.bak',
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_04.bak'

RESTORE DATABASE ASDirect FROM
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_01.bak',
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_02.bak',
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_03.bak',
DISK='C:\DBA_ANDRES\ASDIRECT\ASDirect_04.bak'
WITH NORECOVERY, STATS = 1,
MOVE 'ASDirect' TO 'C:\DBA_ANDRES\ASDIRECT\ASDirect.mdf',
MOVE 'ASDirect_Data2' TO 'C:\DBA_ANDRES\ASDIRECT\ASDirect_Data2.ndf',
MOVE 'ASDirect_Data3' TO 'C:\DBA_ANDRES\ASDIRECT\ASDirect_Data3.ndf',
MOVE 'ASDirect_Data4' TO 'C:\DBA_ANDRES\ASDIRECT\ASDirect_Data4.ndf',
MOVE 'ASDirect_log' TO 'C:\DBA_ANDRES\ASDIRECT\ASDirect_log.ldf'
GO

RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140831234501.trn' 
WITH  STATS = 1, NORECOVERY
GO

RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140901000004.trn' 
WITH  STATS = 1, NORECOVERY
GO
RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140901001502.trn' 
WITH  STATS = 1, NORECOVERY
GO
RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140901003001.trn' 
WITH  STATS = 1, NORECOVERY
GO


RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140901004501.trn' 
WITH  STATS = 1, NORECOVERY
GO
RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140901010001.trn' 
WITH  STATS = 1, NORECOVERY
GO
RESTORE LOG [ASDirect] 
FROM  DISK = N'C:\DBA_ANDRES\ASDIRECT\ASDirect_20140901011502.trn' 
WITH  STATS = 1, RECOVERY, STOPAT = 'Aug 31, 2014 10:09:00 AM' 
GO