USE [master]
GO

CREATE DATABASE ACCESOS_SNAPSHOT ON
( NAME = N'ACCESOS_Data_001', FILENAME = N'P:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_001.snap'), 
( NAME = N'ACCESOS_Data_002', FILENAME = N'U:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_002.snap'), 
( NAME = N'ACCESOS_Data_003', FILENAME = N'V:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_003.snap'), 
( NAME = N'ACCESOS_Data_004', FILENAME = N'W:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_004.snap'), 
( NAME = N'ACCESOS_Data_101', FILENAME = N'P:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_101.snap'), 
( NAME = N'ACCESOS_Data_102', FILENAME = N'U:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_102.snap'), 
( NAME = N'ACCESOS_Data_103', FILENAME = N'V:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_103.snap'), 
( NAME = N'ACCESOS_Data_104', FILENAME = N'W:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_104.snap'), 
( NAME = N'ACCESOS_Data_105', FILENAME = N'P:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_105.snap'), 
( NAME = N'ACCESOS_Data_106', FILENAME = N'U:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_106.snap'), 
( NAME = N'ACCESOS_Data_107', FILENAME = N'V:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_107.snap'), 
( NAME = N'ACCESOS_Data_108', FILENAME = N'W:\BACKUP_FULL\ACCESOS_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF ACCESOS

CREATE DATABASE ASIENTOS_SNAPSHOT ON
( NAME = N'ASIENTOS_Data_001', FILENAME = N'P:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_001.snap'), 
( NAME = N'ASIENTOS_Data_002', FILENAME = N'U:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_002.snap'), 
( NAME = N'ASIENTOS_Data_003', FILENAME = N'V:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_003.snap'), 
( NAME = N'ASIENTOS_Data_004', FILENAME = N'W:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_004.snap'), 
( NAME = N'ASIENTOS_Data_101', FILENAME = N'P:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_101.snap'), 
( NAME = N'ASIENTOS_Data_102', FILENAME = N'U:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_102.snap'), 
( NAME = N'ASIENTOS_Data_103', FILENAME = N'V:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_103.snap'), 
( NAME = N'ASIENTOS_Data_104', FILENAME = N'W:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_104.snap'), 
( NAME = N'ASIENTOS_Data_105', FILENAME = N'P:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_105.snap'), 
( NAME = N'ASIENTOS_Data_106', FILENAME = N'U:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_106.snap'), 
( NAME = N'ASIENTOS_Data_107', FILENAME = N'V:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_107.snap'), 
( NAME = N'ASIENTOS_Data_108', FILENAME = N'W:\BACKUP_FULL\ASIENTOS_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF ASIENTOS


CREATE DATABASE BOF_SNAPSHOT ON
( NAME = N'BOF_Data_001', FILENAME = N'P:\BACKUP_FULL\BOF_SNAPSHOT_Data_001.snap'), 
( NAME = N'BOF_Data_002', FILENAME = N'U:\BACKUP_FULL\BOF_SNAPSHOT_Data_002.snap'), 
( NAME = N'BOF_Data_003', FILENAME = N'V:\BACKUP_FULL\BOF_SNAPSHOT_Data_003.snap'), 
( NAME = N'BOF_Data_004', FILENAME = N'W:\BACKUP_FULL\BOF_SNAPSHOT_Data_004.snap'), 
( NAME = N'BOF_Data_101', FILENAME = N'P:\BACKUP_FULL\BOF_SNAPSHOT_Data_101.snap'), 
( NAME = N'BOF_Data_102', FILENAME = N'U:\BACKUP_FULL\BOF_SNAPSHOT_Data_102.snap'), 
( NAME = N'BOF_Data_103', FILENAME = N'V:\BACKUP_FULL\BOF_SNAPSHOT_Data_103.snap'), 
( NAME = N'BOF_Data_104', FILENAME = N'W:\BACKUP_FULL\BOF_SNAPSHOT_Data_104.snap'), 
( NAME = N'BOF_Data_105', FILENAME = N'P:\BACKUP_FULL\BOF_SNAPSHOT_Data_105.snap'), 
( NAME = N'BOF_Data_106', FILENAME = N'U:\BACKUP_FULL\BOF_SNAPSHOT_Data_106.snap'), 
( NAME = N'BOF_Data_107', FILENAME = N'V:\BACKUP_FULL\BOF_SNAPSHOT_Data_107.snap'), 
( NAME = N'BOF_Data_108', FILENAME = N'W:\BACKUP_FULL\BOF_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF BOF


CREATE DATABASE BOLETINES_SNAPSHOT ON
( NAME = N'BOLETINES_Data_001', FILENAME = N'P:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_001.snap'), 
( NAME = N'BOLETINES_Data_002', FILENAME = N'U:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_002.snap'), 
( NAME = N'BOLETINES_Data_003', FILENAME = N'V:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_003.snap'), 
( NAME = N'BOLETINES_Data_004', FILENAME = N'W:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_004.snap'), 
( NAME = N'BOLETINES_Data_101', FILENAME = N'P:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_101.snap'), 
( NAME = N'BOLETINES_Data_102', FILENAME = N'U:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_102.snap'), 
( NAME = N'BOLETINES_Data_103', FILENAME = N'V:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_103.snap'), 
( NAME = N'BOLETINES_Data_104', FILENAME = N'W:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_104.snap'), 
( NAME = N'BOLETINES_Data_105', FILENAME = N'P:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_105.snap'), 
( NAME = N'BOLETINES_Data_106', FILENAME = N'U:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_106.snap'), 
( NAME = N'BOLETINES_Data_107', FILENAME = N'V:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_107.snap'), 
( NAME = N'BOLETINES_Data_108', FILENAME = N'W:\BACKUP_FULL\BOLETINES_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF BOLETINES

CREATE DATABASE CIERRES_SNAPSHOT ON
( NAME = N'CIERRES_Data_001', FILENAME = N'P:\BACKUP_FULL\CIERRES_Data_001.snap'), 
( NAME = N'CIERRES_Data_002', FILENAME = N'U:\BACKUP_FULL\CIERRES_Data_002.snap'), 
( NAME = N'CIERRES_Data_003', FILENAME = N'V:\BACKUP_FULL\CIERRES_Data_003.snap'), 
( NAME = N'CIERRES_Data_004', FILENAME = N'W:\BACKUP_FULL\CIERRES_Data_004.snap'), 
( NAME = N'CIERRES_Data_101', FILENAME = N'P:\BACKUP_FULL\CIERRES_Data_101.snap'), 
( NAME = N'CIERRES_Data_102', FILENAME = N'U:\BACKUP_FULL\CIERRES_Data_102.snap'), 
( NAME = N'CIERRES_Data_103', FILENAME = N'V:\BACKUP_FULL\CIERRES_Data_103.snap'), 
( NAME = N'CIERRES_Data_104', FILENAME = N'W:\BACKUP_FULL\CIERRES_Data_104.snap'), 
( NAME = N'CIERRES_Data_105', FILENAME = N'P:\BACKUP_FULL\CIERRES_Data_105.snap'), 
( NAME = N'CIERRES_Data_106', FILENAME = N'U:\BACKUP_FULL\CIERRES_Data_106.snap'), 
( NAME = N'CIERRES_Data_107', FILENAME = N'V:\BACKUP_FULL\CIERRES_Data_107.snap'), 
( NAME = N'CIERRES_Data_108', FILENAME = N'W:\BACKUP_FULL\CIERRES_Data_108.snap')
AS SNAPSHOT OF CIERRES

CREATE DATABASE COMPRAS_SNAPSHOT ON
( NAME = N'COMPRAS_Data_001', FILENAME = N'P:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_001.snap'), 
( NAME = N'COMPRAS_Data_002', FILENAME = N'U:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_002.snap'), 
( NAME = N'COMPRAS_Data_003', FILENAME = N'V:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_003.snap'), 
( NAME = N'COMPRAS_Data_004', FILENAME = N'W:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_004.snap'), 
( NAME = N'COMPRAS_Data_101', FILENAME = N'P:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_101.snap'), 
( NAME = N'COMPRAS_Data_102', FILENAME = N'U:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_102.snap'), 
( NAME = N'COMPRAS_Data_103', FILENAME = N'V:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_103.snap'), 
( NAME = N'COMPRAS_Data_104', FILENAME = N'W:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_104.snap'), 
( NAME = N'COMPRAS_Data_105', FILENAME = N'P:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_105.snap'), 
( NAME = N'COMPRAS_Data_106', FILENAME = N'U:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_106.snap'), 
( NAME = N'COMPRAS_Data_107', FILENAME = N'V:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_107.snap'), 
( NAME = N'COMPRAS_Data_108', FILENAME = N'W:\BACKUP_FULL\COMPRAS_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF COMPRAS


CREATE DATABASE COTIZACION_SNAPSHOT ON
( NAME = N'COTIZACION_Data_001', FILENAME = N'P:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_001.snap'), 
( NAME = N'COTIZACION_Data_002', FILENAME = N'u:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_002.snap'), 
( NAME = N'COTIZACION_Data_003', FILENAME = N'v:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_003.snap'), 
( NAME = N'COTIZACION_Data_004', FILENAME = N'w:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_004.snap'), 
( NAME = N'COTIZACION_Data_101', FILENAME = N'p:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_101.snap'), 
( NAME = N'COTIZACION_Data_102', FILENAME = N'u:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_102.snap'), 
( NAME = N'COTIZACION_Data_103', FILENAME = N'v:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_103.snap'), 
( NAME = N'COTIZACION_Data_104', FILENAME = N'w:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_104.snap'), 
( NAME = N'COTIZACION_Data_105', FILENAME = N'p:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_105.snap'), 
( NAME = N'COTIZACION_Data_106', FILENAME = N'u:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_106.snap'), 
( NAME = N'COTIZACION_Data_107', FILENAME = N'v:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_107.snap'), 
( NAME = N'COTIZACION_Data_108', FILENAME = N'w:\BACKUP_FULL\COTIZACION_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF COTIZACION

CREATE DATABASE DEPURACION_SNAPSHOT ON
( NAME = N'DEPURACION_Data_001', FILENAME = N'p:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_001.snap'), 
( NAME = N'DEPURACION_Data_002', FILENAME = N'u:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_002.snap'), 
( NAME = N'DEPURACION_Data_003', FILENAME = N'v:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_003.snap'), 
( NAME = N'DEPURACION_Data_004', FILENAME = N'w:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_004.snap'), 
( NAME = N'DEPURACION_Data_005', FILENAME = N'p:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_005.snap'), 
( NAME = N'DEPURACION_Data_006', FILENAME = N'u:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_006.snap'), 
( NAME = N'DEPURACION_Data_007', FILENAME = N'v:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_007.snap'), 
( NAME = N'DEPURACION_Data_008', FILENAME = N'w:\BACKUP_FULL\DEPURACION_SNAPSHOT_Data_008.snap')
AS SNAPSHOT OF DEPURACION

CREATE DATABASE FACTURACION_SNAPSHOT ON
( NAME = N'FACTURACION_Data_001', FILENAME = N'p:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_001.snap'), 
( NAME = N'FACTURACION_Data_002', FILENAME = N'u:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_002.snap'), 
( NAME = N'FACTURACION_Data_003', FILENAME = N'v:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_003.snap'), 
( NAME = N'FACTURACION_Data_004', FILENAME = N'w:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_004.snap'), 
( NAME = N'FACTURACION_Data_101', FILENAME = N'p:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_101.snap'), 
( NAME = N'FACTURACION_Data_102', FILENAME = N'u:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_102.snap'), 
( NAME = N'FACTURACION_Data_103', FILENAME = N'v:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_103.snap'), 
( NAME = N'FACTURACION_Data_104', FILENAME = N'w:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_104.snap'), 
( NAME = N'FACTURACION_Data_105', FILENAME = N'p:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_105.snap'), 
( NAME = N'FACTURACION_Data_106', FILENAME = N'u:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_106.snap'), 
( NAME = N'FACTURACION_Data_107', FILENAME = N'v:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_107.snap'), 
( NAME = N'FACTURACION_Data_108', FILENAME = N'w:\BACKUP_FULL\FACTURACION_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF FACTURACION

CREATE DATABASE GENERAL_SNAPSHOT ON
( NAME = N'GENERAL_Data_001', FILENAME = N'p:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_001.snap'), 
( NAME = N'GENERAL_Data_002', FILENAME = N'u:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_002.snap'), 
( NAME = N'GENERAL_Data_003', FILENAME = N'v:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_003.snap'), 
( NAME = N'GENERAL_Data_004', FILENAME = N'w:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_004.snap'), 
( NAME = N'GENERAL_Data_005', FILENAME = N'p:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_005.snap'), 
( NAME = N'GENERAL_Data_006', FILENAME = N'u:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_006.snap'), 
( NAME = N'GENERAL_Data_007', FILENAME = N'v:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_007.snap'), 
( NAME = N'GENERAL_Data_008', FILENAME = N'w:\BACKUP_FULL\GENERAL_SNAPSHOT_Data_008.snap')
AS SNAPSHOT OF GENERAL

CREATE DATABASE INGRESOS_SNAPSHOT ON
( NAME = N'INGRESOS_Data_001', FILENAME = N'p:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_001.snap'), 
( NAME = N'INGRESOS_Data_002', FILENAME = N'u:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_002.snap'), 
( NAME = N'INGRESOS_Data_003', FILENAME = N'v:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_003.snap'), 
( NAME = N'INGRESOS_Data_004', FILENAME = N'w:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_004.snap'), 
( NAME = N'INGRESOS_Data_101', FILENAME = N'p:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_101.snap'), 
( NAME = N'INGRESOS_Data_102', FILENAME = N'u:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_102.snap'), 
( NAME = N'INGRESOS_Data_103', FILENAME = N'v:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_103.snap'), 
( NAME = N'INGRESOS_Data_104', FILENAME = N'w:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_104.snap'), 
( NAME = N'INGRESOS_Data_105', FILENAME = N'p:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_105.snap'), 
( NAME = N'INGRESOS_Data_106', FILENAME = N'u:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_106.snap'), 
( NAME = N'INGRESOS_Data_107', FILENAME = N'v:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_107.snap'), 
( NAME = N'INGRESOS_Data_108', FILENAME = N'w:\BACKUP_FULL\INGRESOS_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF INGRESOS

CREATE DATABASE MANLIBAADP_SNAPSHOT ON
( NAME = N'MANLIBAADP_Data_001', FILENAME = N'p:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_001.snap'), 
( NAME = N'MANLIBAADP_Data_002', FILENAME = N'u:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_002.snap'), 
( NAME = N'MANLIBAADP_Data_003', FILENAME = N'v:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_003.snap'), 
( NAME = N'MANLIBAADP_Data_004', FILENAME = N'w:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_004.snap'), 
( NAME = N'MANLIBAADP_Data_101', FILENAME = N'p:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_101.snap'), 
( NAME = N'MANLIBAADP_Data_102', FILENAME = N'u:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_102.snap'), 
( NAME = N'MANLIBAADP_Data_103', FILENAME = N'v:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_103.snap'), 
( NAME = N'MANLIBAADP_Data_104', FILENAME = N'w:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_104.snap'), 
( NAME = N'MANLIBAADP_Data_105', FILENAME = N'p:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_105.snap'), 
( NAME = N'MANLIBAADP_Data_106', FILENAME = N'u:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_106.snap'), 
( NAME = N'MANLIBAADP_Data_107', FILENAME = N'v:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_107.snap'), 
( NAME = N'MANLIBAADP_Data_108', FILENAME = N'w:\BACKUP_FULL\MANLIBAADP_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MANLIBAADP

CREATE DATABASE MANLIBACIE_SNAPSHOT ON
( NAME = N'MANLIBACIE_Data_001', FILENAME = N'p:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_001.snap'), 
( NAME = N'MANLIBACIE_Data_002', FILENAME = N'u:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_002.snap'), 
( NAME = N'MANLIBACIE_Data_003', FILENAME = N'v:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_003.snap'), 
( NAME = N'MANLIBACIE_Data_004', FILENAME = N'w:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_004.snap'), 
( NAME = N'MANLIBACIE_Data_101', FILENAME = N'p:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_101.snap'), 
( NAME = N'MANLIBACIE_Data_102', FILENAME = N'u:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_102.snap'), 
( NAME = N'MANLIBACIE_Data_103', FILENAME = N'v:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_103.snap'), 
( NAME = N'MANLIBACIE_Data_104', FILENAME = N'w:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_104.snap'), 
( NAME = N'MANLIBACIE_Data_105', FILENAME = N'p:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_105.snap'), 
( NAME = N'MANLIBACIE_Data_106', FILENAME = N'u:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_106.snap'), 
( NAME = N'MANLIBACIE_Data_107', FILENAME = N'v:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_107.snap'), 
( NAME = N'MANLIBACIE_Data_108', FILENAME = N'w:\BACKUP_FULL\MANLIBACIE_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MANLIBACIE


CREATE DATABASE MANLIBACOM_SNAPSHOT ON
( NAME = N'MANLIBACOM_Data_001', FILENAME = N'p:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_001.snap'), 
( NAME = N'MANLIBACOM_Data_002', FILENAME = N'u:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_002.snap'), 
( NAME = N'MANLIBACOM_Data_003', FILENAME = N'v:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_003.snap'), 
( NAME = N'MANLIBACOM_Data_004', FILENAME = N'w:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_004.snap'), 
( NAME = N'MANLIBACOM_Data_101', FILENAME = N'p:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_101.snap'), 
( NAME = N'MANLIBACOM_Data_102', FILENAME = N'u:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_102.snap'), 
( NAME = N'MANLIBACOM_Data_103', FILENAME = N'v:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_103.snap'), 
( NAME = N'MANLIBACOM_Data_104', FILENAME = N'w:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_104.snap'), 
( NAME = N'MANLIBACOM_Data_105', FILENAME = N'p:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_105.snap'), 
( NAME = N'MANLIBACOM_Data_106', FILENAME = N'u:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_106.snap'), 
( NAME = N'MANLIBACOM_Data_107', FILENAME = N'v:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_107.snap'), 
( NAME = N'MANLIBACOM_Data_108', FILENAME = N'w:\BACKUP_FULL\MANLIBACOM_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MANLIBACOM

CREATE DATABASE MANLIBACOT_SNAPSHOT ON
( NAME = N'MANLIBACOT_Data_001', FILENAME = N'p:\BACKUP_FULL\MANLIBACOT_Data_001.snap'), 
( NAME = N'MANLIBACOT_Data_002', FILENAME = N'u:\BACKUP_FULL\MANLIBACOT_Data_002.snap'), 
( NAME = N'MANLIBACOT_Data_003', FILENAME = N'v:\BACKUP_FULL\MANLIBACOT_Data_003.snap'), 
( NAME = N'MANLIBACOT_Data_004', FILENAME = N'w:\BACKUP_FULL\MANLIBACOT_Data_004.snap'), 
( NAME = N'MANLIBACOT_Data_101', FILENAME = N'p:\BACKUP_FULL\MANLIBACOT_Data_101.snap'), 
( NAME = N'MANLIBACOT_Data_102', FILENAME = N'u:\BACKUP_FULL\MANLIBACOT_Data_102.snap'), 
( NAME = N'MANLIBACOT_Data_103', FILENAME = N'v:\BACKUP_FULL\MANLIBACOT_Data_103.snap'), 
( NAME = N'MANLIBACOT_Data_104', FILENAME = N'w:\BACKUP_FULL\MANLIBACOT_Data_104.snap'), 
( NAME = N'MANLIBACOT_Data_105', FILENAME = N'p:\BACKUP_FULL\MANLIBACOT_Data_105.snap'), 
( NAME = N'MANLIBACOT_Data_106', FILENAME = N'u:\BACKUP_FULL\MANLIBACOT_Data_106.snap'), 
( NAME = N'MANLIBACOT_Data_107', FILENAME = N'v:\BACKUP_FULL\MANLIBACOT_Data_107.snap'), 
( NAME = N'MANLIBACOT_Data_108', FILENAME = N'w:\BACKUP_FULL\MANLIBACOT_Data_108.snap')
AS SNAPSHOT OF MANLIBACOT

CREATE DATABASE MANLIBASGL_SNAPSHOT ON
( NAME = N'MANLIBASGL_Data_001', FILENAME = N'p:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_001.snap'), 
( NAME = N'MANLIBASGL_Data_002', FILENAME = N'u:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_002.snap'), 
( NAME = N'MANLIBASGL_Data_003', FILENAME = N'v:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_003.snap'), 
( NAME = N'MANLIBASGL_Data_004', FILENAME = N'w:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_004.snap'), 
( NAME = N'MANLIBASGL_Data_101', FILENAME = N'p:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_101.snap'), 
( NAME = N'MANLIBASGL_Data_102', FILENAME = N'u:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_102.snap'), 
( NAME = N'MANLIBASGL_Data_103', FILENAME = N'v:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_103.snap'), 
( NAME = N'MANLIBASGL_Data_104', FILENAME = N'w:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_104.snap'), 
( NAME = N'MANLIBASGL_Data_105', FILENAME = N'p:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_105.snap'), 
( NAME = N'MANLIBASGL_Data_106', FILENAME = N'u:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_106.snap'), 
( NAME = N'MANLIBASGL_Data_107', FILENAME = N'v:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_107.snap'), 
( NAME = N'MANLIBASGL_Data_108', FILENAME = N'w:\BACKUP_FULL\MANLIBASGL_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MANLIBASGL


CREATE DATABASE MNA_SNAPSHOT ON 
( NAME = N'MNA_Data_001', FILENAME = N'p:\BACKUP_FULL\MNA_SNAPSHOT_Data_001.snap'), 
( NAME = N'MNA_Data_002', FILENAME = N'u:\BACKUP_FULL\MNA_SNAPSHOT_Data_002.snap'), 
( NAME = N'MNA_Data_003', FILENAME = N'v:\BACKUP_FULL\MNA_SNAPSHOT_Data_003.snap'), 
( NAME = N'MNA_Data_004', FILENAME = N'w:\BACKUP_FULL\MNA_SNAPSHOT_Data_004.snap'),
( NAME = N'MNA_Data_101', FILENAME = N'p:\BACKUP_FULL\MNA_SNAPSHOT_Data_101.snap'),
( NAME = N'MNA_Data_102', FILENAME = N'u:\BACKUP_FULL\MNA_SNAPSHOT_Data_102.snap'),
( NAME = N'MNA_Data_103', FILENAME = N'v:\BACKUP_FULL\MNA_SNAPSHOT_Data_103.snap'),
( NAME = N'MNA_Data_104', FILENAME = N'w:\BACKUP_FULL\MNA_SNAPSHOT_Data_104.snap'),
( NAME = N'MNA_Data_105', FILENAME = N'p:\BACKUP_FULL\MNA_SNAPSHOT_Data_105.snap'),
( NAME = N'MNA_Data_106', FILENAME = N'u:\BACKUP_FULL\MNA_SNAPSHOT_Data_106.snap'),
( NAME = N'MNA_Data_107', FILENAME = N'v:\BACKUP_FULL\MNA_SNAPSHOT_Data_107.snap'),
( NAME = N'MNA_Data_108', FILENAME = N'w:\BACKUP_FULL\MNA_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MNA


CREATE DATABASE MNL_SNAPSHOT ON 
( NAME = N'MNL_Data_001', FILENAME = N'p:\BACKUP_FULL\MNL_SNAPSHOT_Data_001.snap'), 
( NAME = N'MNL_Data_002', FILENAME = N'u:\BACKUP_FULL\MNL_SNAPSHOT_Data_002.snap'), 
( NAME = N'MNL_Data_003', FILENAME = N'v:\BACKUP_FULL\MNL_SNAPSHOT_Data_003.snap'), 
( NAME = N'MNL_Data_004', FILENAME = N'w:\BACKUP_FULL\MNL_SNAPSHOT_Data_004.snap'),
( NAME = N'MNL_Data_101', FILENAME = N'p:\BACKUP_FULL\MNL_SNAPSHOT_Data_101.snap'),
( NAME = N'MNL_Data_102', FILENAME = N'u:\BACKUP_FULL\MNL_SNAPSHOT_Data_102.snap'),
( NAME = N'MNL_Data_103', FILENAME = N'v:\BACKUP_FULL\MNL_SNAPSHOT_Data_103.snap'),
( NAME = N'MNL_Data_104', FILENAME = N'w:\BACKUP_FULL\MNL_SNAPSHOT_Data_104.snap'),
( NAME = N'MNL_Data_105', FILENAME = N'p:\BACKUP_FULL\MNL_SNAPSHOT_Data_105.snap'),
( NAME = N'MNL_Data_106', FILENAME = N'u:\BACKUP_FULL\MNL_SNAPSHOT_Data_106.snap'),
( NAME = N'MNL_Data_107', FILENAME = N'v:\BACKUP_FULL\MNL_SNAPSHOT_Data_107.snap'),
( NAME = N'MNL_Data_108', FILENAME = N'w:\BACKUP_FULL\MNL_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MNL

CREATE DATABASE MNP_SNAPSHOT ON
( NAME = N'MNP_Data_001', FILENAME = N'P:\BACKUP_FULL\MNP_SNAPSHOT_Data_001.snap'), 
( NAME = N'MNP_Data_002', FILENAME = N'U:\BACKUP_FULL\MNP_SNAPSHOT_Data_002.snap'), 
( NAME = N'MNP_Data_003', FILENAME = N'V:\BACKUP_FULL\MNP_SNAPSHOT_Data_003.snap'), 
( NAME = N'MNP_Data_004', FILENAME = N'W:\BACKUP_FULL\MNP_SNAPSHOT_Data_004.snap'), 
( NAME = N'MNP_Data_101', FILENAME = N'P:\BACKUP_FULL\MNP_SNAPSHOT_Data_101.snap'), 
( NAME = N'MNP_Data_102', FILENAME = N'U:\BACKUP_FULL\MNP_SNAPSHOT_Data_102.snap'), 
( NAME = N'MNP_Data_103', FILENAME = N'V:\BACKUP_FULL\MNP_SNAPSHOT_Data_103.snap'), 
( NAME = N'MNP_Data_104', FILENAME = N'W:\BACKUP_FULL\MNP_SNAPSHOT_Data_104.snap'), 
( NAME = N'MNP_Data_105', FILENAME = N'P:\BACKUP_FULL\MNP_SNAPSHOT_Data_105.snap'), 
( NAME = N'MNP_Data_106', FILENAME = N'U:\BACKUP_FULL\MNP_SNAPSHOT_Data_106.snap'), 
( NAME = N'MNP_Data_107', FILENAME = N'V:\BACKUP_FULL\MNP_SNAPSHOT_Data_107.snap'), 
( NAME = N'MNP_Data_108', FILENAME = N'W:\BACKUP_FULL\MNP_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF MNP

CREATE DATABASE [SAC_SNAPSHOT] ON
( NAME = N'SAC_Data_001', FILENAME = N'p:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_001.snap'), 
( NAME = N'SAC_Data_002', FILENAME = N'u:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_002.snap'), 
( NAME = N'SAC_Data_003', FILENAME = N'v:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_003.snap'), 
( NAME = N'SAC_Data_004', FILENAME = N'w:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_004.snap'), 
( NAME = N'SAC_Data_101', FILENAME = N'P:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_101.snap'), 
( NAME = N'SAC_Data_102', FILENAME = N'u:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_102.snap'), 
( NAME = N'SAC_Data_103', FILENAME = N'v:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_103.snap'), 
( NAME = N'SAC_Data_104', FILENAME = N'w:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_104.snap'), 
( NAME = N'SAC_Data_105', FILENAME = N'P:\BACKUP_FULL\data\SAC_SNAPSHOT_Data_105.snap'), 
( NAME = N'SAC_Data_106', FILENAME = N'u:\BACKUP_FULL\Data\SAC_SNAPSHOT_Data_106.snap'), 
( NAME = N'SAC_Data_107', FILENAME = N'v:\BACKUP_FULL\Data\SAC_SNAPSHOT_Data_107.snap'), 
( NAME = N'SAC_Data_108', FILENAME = N'w:\BACKUP_FULL\Data\SAC_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF SAC

CREATE DATABASE SGL_SNAPSHOT ON
( NAME = N'SGL_Data_001', FILENAME = N'P:\BACKUP_FULL\SGL_SNAPSHOT_Data_001.snap'), 
( NAME = N'SGL_Data_002', FILENAME = N'U:\BACKUP_FULL\SGL_SNAPSHOT_Data_002.snap'), 
( NAME = N'SGL_Data_003', FILENAME = N'V:\BACKUP_FULL\SGL_SNAPSHOT_Data_003.snap'), 
( NAME = N'SGL_Data_004', FILENAME = N'W:\BACKUP_FULL\SGL_SNAPSHOT_Data_004.snap'), 
( NAME = N'SGL_Data_101', FILENAME = N'P:\BACKUP_FULL\SGL_SNAPSHOT_Data_101.snap'), 
( NAME = N'SGL_Data_102', FILENAME = N'U:\BACKUP_FULL\SGL_SNAPSHOT_Data_102.snap'), 
( NAME = N'SGL_Data_103', FILENAME = N'V:\BACKUP_FULL\SGL_SNAPSHOT_Data_103.snap'), 
( NAME = N'SGL_Data_104', FILENAME = N'W:\BACKUP_FULL\SGL_SNAPSHOT_Data_104.snap'), 
( NAME = N'SGL_Data_105', FILENAME = N'P:\BACKUP_FULL\SGL_SNAPSHOT_Data_105.snap'), 
( NAME = N'SGL_Data_106', FILENAME = N'U:\BACKUP_FULL\SGL_SNAPSHOT_Data_106.snap'), 
( NAME = N'SGL_Data_107', FILENAME = N'V:\BACKUP_FULL\SGL_SNAPSHOT_Data_107.snap'), 
( NAME = N'SGL_Data_108', FILENAME = N'W:\BACKUP_FULL\SGL_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF SGL

CREATE DATABASE SGLDV_SNAPSHOT ON
( NAME = N'SGLDV_Data_001', FILENAME = N'P:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_001.snap'), 
( NAME = N'SGLDV_Data_002', FILENAME = N'U:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_002.snap'), 
( NAME = N'SGLDV_Data_003', FILENAME = N'V:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_003.snap'), 
( NAME = N'SGLDV_Data_004', FILENAME = N'W:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_004.snap'), 
( NAME = N'SGLDV_Data_101', FILENAME = N'P:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_101.snap'), 
( NAME = N'SGLDV_Data_102', FILENAME = N'U:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_102.snap'), 
( NAME = N'SGLDV_Data_103', FILENAME = N'V:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_103.snap'), 
( NAME = N'SGLDV_Data_104', FILENAME = N'W:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_104.snap'), 
( NAME = N'SGLDV_Data_105', FILENAME = N'P:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_105.snap'), 
( NAME = N'SGLDV_Data_106', FILENAME = N'U:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_106.snap'), 
( NAME = N'SGLDV_Data_107', FILENAME = N'V:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_107.snap'), 
( NAME = N'SGLDV_Data_108', FILENAME = N'W:\BACKUP_FULL\SGLDV_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF SGLDV

CREATE DATABASE SIPDWH_SNAPSHOT ON
( NAME = N'SIPDWH_Data_001', FILENAME = N'P:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_001.snap'), 
( NAME = N'SIPDWH_Data_002', FILENAME = N'U:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_002.snap'), 
( NAME = N'SIPDWH_Data_003', FILENAME = N'V:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_003.snap'), 
( NAME = N'SIPDWH_Data_004', FILENAME = N'W:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_004.snap'), 
( NAME = N'SIPDWH_Data_005', FILENAME = N'P:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_005.snap'), 
( NAME = N'SIPDWH_Data_006', FILENAME = N'U:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_006.snap'), 
( NAME = N'SIPDWH_Data_007', FILENAME = N'V:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_007.snap'), 
( NAME = N'SIPDWH_Data_008', FILENAME = N'W:\BACKUP_FULL\SIPDWH_SNAPSHOT_Data_008.snap')
AS SNAPSHOT OF SIPDWH

CREATE DATABASE TRANSFORMACION_SNAPSHOT ON
( NAME = N'TRANSFORMACION_Data_001', FILENAME = N'P:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_001.snap'), 
( NAME = N'TRANSFORMACION_Data_002', FILENAME = N'U:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_002.snap'), 
( NAME = N'TRANSFORMACION_Data_003', FILENAME = N'V:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_003.snap'), 
( NAME = N'TRANSFORMACION_Data_004', FILENAME = N'W:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_004.snap'), 
( NAME = N'TRANSFORMACION_Data_101', FILENAME = N'P:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_101.snap'), 
( NAME = N'TRANSFORMACION_Data_102', FILENAME = N'U:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_102.snap'), 
( NAME = N'TRANSFORMACION_Data_103', FILENAME = N'V:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_103.snap'), 
( NAME = N'TRANSFORMACION_Data_104', FILENAME = N'W:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_104.snap'), 
( NAME = N'TRANSFORMACION_Data_105', FILENAME = N'P:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_105.snap'), 
( NAME = N'TRANSFORMACION_Data_106', FILENAME = N'U:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_106.snap'), 
( NAME = N'TRANSFORMACION_Data_107', FILENAME = N'V:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_107.snap'), 
( NAME = N'TRANSFORMACION_Data_108', FILENAME = N'W:\BACKUP_FULL\TRANSFORMACION_SNAPSHOT_Data_108.snap')
AS SNAPSHOT OF TRANSFORMACION