USE master
go

DROP DATABASE ACCESOS_SNAPSHOT 

DROP DATABASE ASIENTOS_SNAPSHOT 

DROP DATABASE BOF_SNAPSHOT 

DROP DATABASE BOLETINES_SNAPSHOT 

DROP DATABASE CIERRES_SNAPSHOT 

DROP DATABASE COMPRAS_SNAPSHOT

DROP DATABASE COTIZACION_SNAPSHOT 

DROP DATABASE DEPURACION_SNAPSHOT 

DROP DATABASE FACTURACION_SNAPSHOT 

DROP DATABASE GENERAL_SNAPSHOT 

DROP DATABASE INGRESOS_SNAPSHOT 

DROP DATABASE MANLIBAADP_SNAPSHOT 

DROP DATABASE MANLIBACIE_SNAPSHOT 

DROP DATABASE MANLIBACOM_SNAPSHOT 

DROP DATABASE MANLIBACOT_SNAPSHOT 

DROP DATABASE MANLIBASGL_SNAPSHOT

DROP DATABASE MNL_SNAPSHOT

DROP DATABASE MNP_SNAPSHOT

DROP DATABASE MNA_SNAPSHOT

DROP DATABASE SAC_SNAPSHOT

DROP DATABASE SGLDV_SNAPSHOT

DROP DATABASE SGL_SNAPSHOT

DROP DATABASE SIPDWH_SNAPSHOT

DROP DATABASE TRANSFORMACION_SNAPSHOT