USE master
go

RESTORE DATABASE ACCESOS
FROM DATABASE_SNAPSHOT='ACCESOS_SNAPSHOT' 

RESTORE DATABASE ASIENTOS_SNAPSHOT 
FROM DATABASE_SNAPSHOT='ASIENTOS_SNAPSHOT'

RESTORE DATABASE BOF_SNAPSHOT 
FROM DATABASE_SNAPSHOT='BOF_SNAPSHOT'

RESTORE DATABASE BOLETINES_SNAPSHOT 
FROM DATABASE_SNAPSHOT='BOLETINES_SNAPSHOT'

RESTORE DATABASE CIERRES_SNAPSHOT 
FROM DATABASE_SNAPSHOT='CIERRES_SNAPSHOT'

RESTORE DATABASE COMPRAS_SNAPSHOT
FROM DATABASE_SNAPSHOT='COMPRAS_SNAPSHOT'

RESTORE DATABASE COTIZACION_SNAPSHOT 
FROM DATABASE_SNAPSHOT='COTIZACION_SNAPSHOT'

RESTORE DATABASE DEPURACION_SNAPSHOT 
FROM DATABASE_SNAPSHOT='DEPURACION_SNAPSHOT'

RESTORE DATABASE FACTURACION_SNAPSHOT 
FROM DATABASE_SNAPSHOT='FACTURACION_SNAPSHOT'

RESTORE DATABASE GENERAL_SNAPSHOT 
FROM DATABASE_SNAPSHOT='GENERAL_SNAPSHOT'

RESTORE DATABASE INGRESOS_SNAPSHOT 
FROM DATABASE_SNAPSHOT='INGRESOS_SNAPSHOT'

RESTORE DATABASE MANLIBAADP_SNAPSHOT 
FROM DATABASE_SNAPSHOT='MANLIBAADP_SNAPSHOT'

RESTORE DATABASE MANLIBACIE_SNAPSHOT 
FROM DATABASE_SNAPSHOT='MANLIBACIE_SNAPSHOT'

RESTORE DATABASE MANLIBACOM_SNAPSHOT 
FROM DATABASE_SNAPSHOT='MANLIBACOM_SNAPSHOT'

RESTORE DATABASE MANLIBACOT_SNAPSHOT 
FROM DATABASE_SNAPSHOT='MANLIBACOT_SNAPSHOT'

RESTORE DATABASE MANLIBASGL_SNAPSHOT
FROM DATABASE_SNAPSHOT='MANLIBASGL_SNAPSHOT'

RESTORE DATABASE MNL_SNAPSHOT
FROM DATABASE_SNAPSHOT='MNL_SNAPSHOT'

RESTORE DATABASE MNP_SNAPSHOT
FROM DATABASE_SNAPSHOT='MNP_SNAPSHOT'

RESTORE DATABASE MNA_SNAPSHOT
FROM DATABASE_SNAPSHOT='MNA_SNAPSHOT'

RESTORE DATABASE SAC_SNAPSHOT
FROM DATABASE_SNAPSHOT='SAC_SNAPSHOT'

RESTORE DATABASE SGL_SNAPSHOT
FROM DATABASE_SNAPSHOT='SGL_SNAPSHOT'

RESTORE DATABASE SGLDV_SNAPSHOT
FROM DATABASE_SNAPSHOT='SGLDV_SNAPSHOT'

RESTORE DATABASE SIPDWH_SNAPSHOT
FROM DATABASE_SNAPSHOT='SIPDWH_SNAPSHOT'

RESTORE DATABASE TRANSFORMACION_SNAPSHOT
FROM DATABASE_SNAPSHOT='TRANSFORMACION_SNAPSHOT'